#!/bin/sh
# ios/Runner/extract_maps_key.sh

# Resolve paths relative to script location
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR/../.."
ENV_JSON="$PROJECT_ROOT/env.json"
OUTPUT_FILE="$SCRIPT_DIR/../Flutter/Dart-Defines.xcconfig"

# Start with a clean file
echo "// Automatically generated by extract_maps_key.sh. Do not edit." > "$OUTPUT_FILE"

# 1. First, try to extract key from DART_DEFINES if passed by Flutter tool
if [ -n "$DART_DEFINES" ]; then
  # DART_DEFINES is comma-separated base64 encoded items
  IFS=',' read -r -a define_items <<< "$DART_DEFINES"
  for item in "${define_items[@]}"; do
    if [ -n "$item" ]; then
      decoded=$(echo "$item" | base64 --decode 2>/dev/null || echo "")
      if [[ "$decoded" == GOOGLE_MAPS_API_KEY=* ]]; then
        MAPS_KEY="${decoded#*=}"
        echo "TrackLog Build: Extracted GOOGLE_MAPS_API_KEY from DART_DEFINES"
        echo "GOOGLE_MAPS_API_KEY = $MAPS_KEY" >> "$OUTPUT_FILE"
        exit 0
      fi
    fi
  done
fi

# 2. Fall back to reading env.json if DART_DEFINES didn't yield the key
if [ -f "$ENV_JSON" ]; then
  # Read GOOGLE_MAPS_API_KEY from env.json
  MAPS_KEY=$(grep -o '"GOOGLE_MAPS_API_KEY"[[:space:]]*:[[:space:]]*"[^"]*' "$ENV_JSON" | cut -d'"' -f4)
  if [ -n "$MAPS_KEY" ]; then
    echo "TrackLog Build: Extracted GOOGLE_MAPS_API_KEY from env.json"
    echo "GOOGLE_MAPS_API_KEY = $MAPS_KEY" >> "$OUTPUT_FILE"
    exit 0
  fi
fi

echo "TrackLog Build: Warning - GOOGLE_MAPS_API_KEY not found in DART_DEFINES or env.json"
